name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Copy .env file
        run: cp .env.example .env
      #
      - name: Generate application key
        run: php artisan key:generate

      - name: Create test database file
        run: touch database/database_test.sqlite

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
